### PR TITLE
Reuse the token set by hyper for reqwest calls

### LINKED ISSUE #66: blobs: authentication is broken
Since the token is appended to the request headers of the *hyper* client, which is not considered *reqwest*, #65 broke authenticated calls for blobs.

### PR DESCRIPTION
**Pull request by steveeJ**
Depends on #69.
Fixes #66

### CODE REVIEW

File: src/v2/mod.rs [hunk 1]
```diff
@@ -142,6 +142,21 @@ impl Client {
     }
 }
 
+/// Reqwest related implementation
+impl Client {
+    /// Takes reqwest's async RequestBuilder and injects an authentication header if a token is present
+    fn build_reqwest(
```
Comment (lucab) [inline src/v2/mod.rs]: Let's have this in the already existing `impl Client` block above, as it will eventually be moved there anyway.
